# flask-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: web-db-example
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-app
  type: LoadBalancer

